### ISSUE TITLE
Todo for Kadah

### ISSUE THREAD

**Issue by JasXSL** [JasXSL/VibHub-ESP32#2]
- [x] Re-implement motor reversal. The old code is there, just commented out, search the code for "kadah".
- [x] Add pwm.enable and pwm.disable to the new PWM system.
- [x] Try to implement OTA

**Comment by Kadah** [comment]
pwm.enable/pwm.disable globally turns off the motor driver enable line. I use this for state changes. On the ESP8266 board, the power on state of the PWM chip might cause the motor outputs to be on, the enabled line makes sure our outputs are actually off when we expect them to be (setup mode, offline, etc). Only requires a single digital line, so I plan to keep it.

**Comment by Kadah** [comment]
OTA is entirely possible. Need to discuss how we want it to be initiated. Currently have it server initiated via "ota" socket event with "file" and "md5" fields, bin files hosted on github releases.

An autoupdater is also possible. Could have it check for updates on connect and download from the server.

Basically anything where it downloads the bin from a webserver should be doable. Using HTTPS would be a good idea and long term we might want the update server to have its own self-signed cacert with a very long expiry as the public key needs to be baked in to the firmware.

**Comment by JasXSL** [comment]
Having an app handle the updates via sockets is fine. The update host needs to be hardcoded though to prevent abuse, as any app can trigger this update. What I think should be done:

Method A:

1. When the VibHub device gains internet accessibility, it fetches the firmware version. Could be from a hardcoded git repo or somewhere on vibhub.io. People who want a custom firmware will have to upload it the old fashioned way.
2. When a VibHub device sends the online message to an app, include a current version and latest version setting.
3. The app decides what it wants to do with these. It can display an "update available message"
4. The app can send an update command via websockets or REST. When the device receives this, and if the device actually has an update available, begin the update.
5. While updating, flash the LED in some color if possible to indicate that they should not power down the device.

Method B:

1. The device checks the version when booted.
2. If an update is available, flash a color a few times.
3. Quick-press the config button to start the update.

**Comment by Kadah** [comment]
ESP8266 updates downloading over HTTP(S) is not proving to be doable. It should work, but I cannot get it to work. The few server examples are old and predate the current ESP8266httpUpdate that requires a x-MD5. Even after adding that, the received firmware bin is failing the magic header tests and I cannot track down why.
I'm giving up making the ESP8266 support being able to download firmware updates itself. I might test using the ESP8266's internal web server to upload bins to it instead via a browser.

Since we are EOLing the ESP8266 version for the ESP32, ez updating isn't a huge concern.
