### ISSUE TITLE
Jas todo list

### ISSUE THREAD

**Issue by JasXSL** [JasXSL/VibHub-ESP32#3]
- [x] Implement HW random
- [x] The CSS is bork in the latest version of wifimanager. Fix this.
- [x] Put ESP in deep sleep if autoconnect fails. Maybe show a permanent red light of death if doable.
- [x] Improve tweening so each repeat doesn't need to generate an additional stage in the tween, conserving memory.
- [x] Captive portal E-manual
